# Generated by Django 2.2.16 on 2022-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220414_0942'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user',), name='unique user'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='sqlite3',
        ),
    ]
