# Generated by Django 2.2.16 on 2022-04-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220415_1944'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user',), name='unique user'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='db0',
        ),
    ]
