# Generated by Django 2.2.16 on 2022-04-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220415_1949'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user_id',), name='unique user'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
