# Generated by Django 2.2.16 on 2022-04-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20220415_2106'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='posts_follow',
        ),
    ]
