# Generated by Django 2.2.16 on 2022-04-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20220416_1434'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='sqlite3',
        ),
    ]
