# Generated by Django 2.2.16 on 2022-04-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20220416_1505'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
